photographyapp/urls.py
from django.urls import path
from .views import *

app_name = "photographyapp"

urlpatterns = [
    path("", ClientHomeView.as_view(), name="clienthome"),
    path("tearsheet/", ClientTearSheetView.as_view(), name="clienttearsheet"),
    path("about", AboutView.as_view(), name="about"),
    path("contact", ContactView.as_view(), name="contact"),
    path("photo/<int:pk>/", ClientCategoryDetailView.as_view(),
         name="clientcategorydetail"),
    path('projects/', ClientProjectListView.as_view(),
         name="clientprojectlist"),



]

photographyproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photographyapp.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photographyapp/models.py
from django.db import models


class PersonalInformation(models.Model):
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to="personalbio")
    nickname = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to="personalbio")
    email = models.EmailField()
    mobile = models.CharField(max_length=50)
    address = models.CharField(max_length=500)
    education = models.CharField(max_length=200)
    about = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Slider(models.Model):
    title = models.CharField(max_length=200)
    caption = models.CharField(max_length=200)
    image = models.ImageField(upload_to="sliders")

    def __str__(self):
        return self.title


class Award(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="awards")
    date = models.DateField()
    description = models.TextField()
    provided_by = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="category", null=True, blank=True)

    def __str__(self):
        return self.title


class Photo(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="photos")
    caption = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    link = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


STATUS = (
    ('ongoing', 'On going project'),
    ('completed', 'Completed project'),
)


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    status = models.CharField(max_length=200, choices=STATUS)
    completion_pct = models.PositiveIntegerField(null=True, blank=True)

    def __str__(self):
        return self.title


class Message(models.Model):
    sender = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender


class Testimonial(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="testimonial")
    sayings = models.CharField(max_length=600)
    current_engagement = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Tearsheet(models.Model):
    image = models.ImageField(upload_to="category")

    def __str__(self):
        return str(self.id)


class About(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to="image")
    description = models.TextField()

    def __str__(self):
        return self.name

photographyapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import *
from .forms import *
from .models import *


class ClientMixin(object):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['persinfo'] = PersonalInformation.objects.first()
        context['aboutinfo'] = About.objects.all()
        context['allcategories'] = Category.objects.all()
        return context


class ClientHomeView(ClientMixin, TemplateView):
    template_name = "clienttemplates/clienthome.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allsliders'] = Slider.objects.all()
        context['awards'] = Award.objects.all()
        context['alltestimonials'] = Testimonial.objects.all()
        context['page'] = "home"
        return context


class ClientCategoryDetailView(ClientMixin, DetailView):
    template_name = "clienttemplates/clientcategorydetail.html"
    model = Category
    context_object_name = "categoryobject"


class AboutView(ClientMixin, TemplateView):
    template_name = "clienttemplates/about.html"


class ContactView(ClientMixin, TemplateView):
    template_name = "clienttemplates/contact.html"


class ClientProjectListView(ClientMixin, ListView):
    template_name = "clienttemplates/clientprojectlist.html"
    queryset = Project.objects.all()
    context_object_name = "projects"

    def get_queryset(self):
        status = self.request.GET['status']
        print(status, "********************************")
        return Project.objects.filter(status=status)


class ClientTearSheetView(ClientMixin, ListView):
    template_name = "clienttemplates/clienttearsheet.html"
    queryset = Tearsheet.objects.all()
    context_object_name = "alltearsheet"

templates/clienttemplates/about.html
{% extends 'clienttemplates/base.html' %}
{% block about %}active{% endblock %}

{% block content %}

<div class="banner_bottom">
	<div class="container">
		<h3 class="tittle_w3ls">About me</h3>
		<img src="{{persinfo.image.url}}" class="img-responsive">
		<h3>{{persinfo.name}}</h3>
		<p>{{persinfo.about}}</p>
	</div>
</div>






{% endblock %}

templates/clienttemplates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>Gyanendra Bhattrai-The Photography</title>

	<!--/tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Gyanendra Bhattrai, dhiren photography" />
	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--//tags -->
	<link href="{% static 'clientstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static 'clientstatic/css/chocolat.css' %}" type="text/css" media="screen">
	<link href="{% static 'clientstatic/css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css' />
	<link href="{% static 'clientstatic/css/fontawesome-all.css' %}" rel="stylesheet">
	<!-- //for bootstrap working -->
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,600,600i,700" rel="stylesheet">
</head>

<body>
	<div class="top_header" id="home">
		<!-- Fixed navbar -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="nav_top_fx_w3layouts_agileits">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
					<div class="logo">
						<h2> <a class="navbar-brand" href="{% url 'photographyapp:clienthome' %}"><i class="fas fa-camera" aria-hidden="true"></i> {{persinfo.name}} <span class="desc">The Photography</span></a></h2>
					</div>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<div class="nav_right_top_agile_w3ls">
						<ul class="nav navbar-nav">
							<li class="{% block homepage %}{% endblock %}"><a href="{% url 'photographyapp:clienthome' %}">Home</a></li>
							<li class="{% block about %}{% endblock %}"><a class="" href="{% url 'photographyapp:about' %}">About</a></li>
							<li class="{% block contact %}{% endblock %}"><a class="scroll" href="{% url 'photographyapp:contact' %}">Contact</a></li>
							<li class="dropdown {% block photo %}{% endblock %}">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Photos and Videos <span class="caret"></span></a>
								<ul class="dropdown-menu">
									{% for category in allcategories %}
									<li><a class="scroll" href="{% url 'photographyapp:clientcategorydetail' category.id %}">{{category.title}}</a></li>
									{% endfor %}
								</ul>
							</li>
						
							<li class="dropdown {% block project %}{% endblock %}">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a class="scroll" href="{% url 'photographyapp:clientprojectlist' %}?status=ongoing">On going projects</a></li>
									<li><a class="scroll" href="{% url 'photographyapp:clientprojectlist' %}?status=completed">Completed projects</a></li>
								</ul>
							</li>
								<li class="dropdown {% block abc %}{% endblock %}">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Check these too<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a class="scroll" href="{% url 'photographyapp:clienthome' %}#awardsssss">Awards & Acknowledgement</a></li>
									<li><a class="scroll" href="{% url 'photographyapp:clienthome' %}#test">Testimonial</a></li>
									<li><a class="scroll" href="{% url 'photographyapp:clienttearsheet' %}#test">Tear Sheet</a></li>
								</ul>
							</li>
							<li><a class="scroll" href="#team"></a></li>
							
						</ul>
					</div>
				</div>
				<!--/.nav-collapse -->
			</div>
		</nav>
		<div class="clearfix"></div>
	</div>

	{% block content %}

	{% endblock %}

	<!-- footer -->
	<div class="footer" id="contact">
		<div class="footer_inner_info">
			<!--/tabs-->
			{% block footer %}
			{% endblock %}
			<!--//tabs-->
			<div class="clearfix"> </div>
			<ul class="social-nav model-3d-0 footer-social social two">
				<li>
					<a href="#" class="facebook">
						<div class="front"><i class="fab fa-facebook-f" aria-hidden="true"></i></div>
						<div class="back"><i class="fab fa-facebook-f" aria-hidden="true"></i></div>
					</a>
				</li>
				<li>
					<a href="#" class="twitter">
						<div class="front"><i class="fab fa-twitter" aria-hidden="true"></i></div>
						<div class="back"><i class="fab fa-twitter" aria-hidden="true"></i></div>
					</a>
				</li>
				<li>
					<a href="#" class="instagram">
						<div class="front"><i class="fab fa-instagram" aria-hidden="true"></i></div>
						<div class="back"><i class="fab fa-instagram" aria-hidden="true"></i></div>
					</a>
				</li>
				
			</ul>
			<p class="copy-right">&copy 2019. All rights reserved | Design by <a href="http://w3layouts.com/">Dhirendra Shah</a></p>
		</div>
	</div>
	<!-- //footer -->
	<script type="text/javascript" src="{% static 'clientstatic/js/jquery-2.2.3.min.js' %}"></script>
	<script src="{% static 'clientstatic/js/responsiveslides.min.js' %}"></script>
	<script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager: true,
				nav: false,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
	</script>
	<script type="text/javascript" src="{% static 'clientstatic/js/bootstrap.js' %}"></script>

	<script type="text/javascript" src="{% static 'clientstatic/js/all.js' %}"></script>
	<script>
		$('ul.dropdown-menu li').hover(function () {
			$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(500);
		}, function () {
			$(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(500);
		});
	</script>

	<!-- js -->
	<!--/tooltip -->
	<script>
		$(function () {
			$('[data-toggle="tooltip"]').tooltip({
				trigger: 'manual'
			}).tooltip('show');
		});

		// $( window ).scroll(function() {   
		// if($( window ).scrollTop() > 10){  // scroll down abit and get the action   
		$(".progress-bar").each(function () {
			each_bar_width = $(this).attr('aria-valuenow');
			$(this).width(each_bar_width + '%');
		});

		//  }  
		// });
	</script>
	<!--//tooltip -->
	<!-- script for responsive tabs -->
	<script src="{% static 'clientstatic/js/easy-responsive-tabs.js' %}"></script>
	<script>
		$(document).ready(function () {
			$('#horizontalTab').easyResponsiveTabs({
				type: 'default', //Types: default, vertical, accordion           
				width: 'auto', //auto or any width like 600px
				fit: true, // 100% fit in a container
				closed: 'accordion', // Start closed if in accordion view
				activate: function (event) { // Callback function if tab is switched
					var $tab = $(this);
					var $info = $('#tabInfo');
					var $name = $('span', $info);
					$name.text($tab.text());
					$info.show();
				}
			});
			$('#verticalTab').easyResponsiveTabs({
				type: 'vertical',
				width: 'auto',
				fit: true
			});
		});
	</script>
	<!--// script for responsive tabs -->

	<!--gallery -->
	<script src="{% static 'clientstatic/js/jquery.chocolat.js' %}"></script>
	<!--light-box-files -->
	<script type="text/javascript">
		$(function () {
			$('.gallery-grid1 a').Chocolat();
		});
	</script>
	<!-- //gallery -->
	<!-- Smooth-Scrolling-JavaScript -->
	<script type="text/javascript" src="{% static 'clientstatic/js/easing.js' %}"></script>
	<script type="text/javascript" src="{% static 'clientstatic/js/move-top.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function ($) {
			$(".scroll, .navbar li a, .footer li a").click(function (event) {
				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
	</script>
	<!-- //Smooth-Scrolling-JavaScript -->
	<script type="text/javascript">
		$(document).ready(function () {
			/*
									var defaults = {
							  			containerID: 'toTop', // fading element id
										containerHoverID: 'toTopHover', // fading element hover id
										scrollSpeed: 1200,
										easingType: 'linear' 
							 		};
									*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<script type="text/javascript">
		$( document ).ready(function() {

  var hashcode = window.location.hash;
  $('html, body').animate({
        scrollTop: $(hashcode).offset().top
    }, 3000);
});
	</script>


	<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>

</body>

</html>

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/base.html' %}
{% load static %}
{% block photo %}active{% endblock %}

{% block content %}
	<!-- banner -->
	<div class="banner_top">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		</div>

	</div>

	<div class="works" id="services">
		<div class="container">
			<h3 class="tittle_w3ls cen">Category: {{categoryobject.title}}</h3>
		</div>
	</div>

	<!--//photographers-->
	<div class="gallery_sec" id="gallery">
		{% for photo in categoryobject.photo_set.all %}
		<div class="col-md-4 col-sm-4 col-xs-4 gal-sec">
			<div class="gallery-grid1">
				<a title="{{photo.title}}" href="{{photo.image.url}}">
						<img src="{{photo.image.url}}" alt=" " class="img-responsive" />
						<div class="p-mask">
						<h4>{{photo.title}}</h4>
							<p>{{photo.caption}}</p>
						</div>
						</a>
			</div>
		</div>
		{% endfor %}
	
		
		
		
		<div class="clearfix"></div>
	</div>

	<div class="works" id="services">
		<div class="container">
			<h3 class="tittle_w3ls cen">Videos</h3>
		</div>
	</div>
	<div class="gallery_sec" id="gallery">
		{% for video in categoryobject.video_set.all %}
		<div class="col-md-6 col-sm-6 col-xs-6 gal-sec">
			<div class="gallery-grid1">
						<iframe width="560" height="315" src="https://www.youtube.com/embed/{{video.link}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
			</div>
		</div>
		{% endfor %}
	
		
		
		
		<div class="clearfix"></div>
	</div>
{% endblock %}

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/base.html' %}
{% load static %}

{% block homepage %}active{% endblock %}

{% block content %}
	<!-- banner -->
	<div class="banner_top">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				{% for slider in allsliders %}
				<li data-target="#myCarousel" data-slide-to="{{forloop.counter}}" {% if forloop.counter == 1 %} class="active"{% endif %}></li>
				{% endfor %}
				
			</ol>
			<div class="carousel-inner" role="listbox">
				{% for slider in allsliders %}
				<div class="item{% if forloop.counter == 1 %} active{% else %} item{{forloop.counter}}{% endif %}" style="background: -webkit-linear-gradient(rgba(23, 22, 23, 0.2), rgba(23, 22, 23, 0.5)), url({{slider.image.url}}) no-repeat;">
					<div class="container">
						<div class="carousel-caption">
							<h3>{{slider.title}}</h3>
							<p>{{slider.caption}}</p>

						</div>
					</div>
				</div>
				{% endfor %}
			</div>
			
	
			<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="fa fa-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span></a>
			<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="fa fa-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
			</a>
		</div>
	</div>

	<div class="banner_bottom">
		<div class="container">
			<h3 class="tittle_w3ls">About me</h3>
			<div class="inner_sec_info_agile_w3_info">
				<div class="last_sec">
					<div class="col-md-8 last-img-info-text">
						<h4>{{persinfo.name}} </h4>
						<p>{{persinfo.about|truncatechars:"300"}}
						</p>
						<div class="ab_button">
							<a class="btn btn-primary btn-lg" href="{% url 'photographyapp:about' %}" role="button">Read More </a>
						</div>
					</div>
					<div class="col-md-4 last-img-info">
						<div class="dodecagon l1">
							<div class="dodecagon-in l1">
								<div class="dodecagon-bg l1" style="background: url({{persinfo.image.url}}) no-repeat 0px 0px;">

								</div>
							</div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="banner_bottom" id="awardsssss">
		<div class="container">
			<h3 class="tittle_w3ls">Awards & Acknowledgement</h3>
			<div class="inner_sec_info_agile_w3_info">
				<div class="last_sec">
						{% for award in awards %}
						<div class="col-md-12" >
									<h3><strong>Title: </strong>{{award.title}}</h3><hr>
									<div class="col-md-3">
										<img src="{{award.image.url}}" class="img-responsive"><hr>
									</div>						
									<h5>{{award.description}}</h5><br>
									<h4><strong>Provided_by:</strong>{{award.provided_by}}</h4>
									<h4><strong>Awarded Date: </strong>{{award.date}}</h4><hr>
						</div>
						{% endfor %}
									
								
						
				</div>
			</div>
		</div>
	</div>
	
	<!--/testimonials-->
	<div class="tesimonials" id="test">
		<div class="container">
			<h3 class="tittle_w3ls cen">Testimonials</h3>
			<div class="inner_sec_info_agile_w3_info">
				<div class="test_grid_sec">
					<div class="col-md-offset-2 col-md-8">
						<div class="carousel slide two" data-ride="carousel" id="quote-carousel">
							<!-- Bottom Carousel Indicators -->
							<ol class="carousel-indicators two">
								{% for testimonial in alltestimonials %}
								<li data-target="#quote-carousel" data-slide-to="{{forloop.counter}}"{% if forloop.counter == 1 %} class="active"{% endif %}></li>
								{% endfor %}
								
							</ol>

							<!-- Carousel Slides / Quotes -->
							<div class="carousel-inner">

								{% for testimonial in alltestimonials %}
								<div class="item {% if forloop.counter == 1 %}active{% endif %}">
									<blockquote>
										<div class="test_grid">
											<div class="col-sm-3 text-center test_img">
												<div class="dodecagon c1">
													<div class="dodecagon-in c1">
														<div class="dodecagon-bg c1" style="background: url({{testimonial.image.url}}) no-repeat 0px 0px;">

														</div>
													</div>
												</div>
											</div>
											<div class="col-sm-9 test_img_info">
												<p><i class="fas fa-quote-left"></i>{{testimonial.sayings}}</p>
												<h6>{{testimonial.name}} ({{testimonial.current_engagement}})</h6>
											</div>
										</div>
									</blockquote>
								</div>
							{% endfor %}
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
		

{% endblock %}

templates/clienttemplates/clientprojectlist.html
{% extends 'clienttemplates/base.html' %}
{% block project %}active{% endblock %}



{% block content %}


	<div class="works" id="services">
		<div class="container">
			<h3 class="tittle_w3ls cen">{{request.GET.status}} Projects</h3>
		</div>
	</div>

<div class="banner_bottom" id="about">
	<div class="container">
		<div class="news-main">
			{% for project in projects %}
				<div class="col-md-6 banner_bottom_left">
					<div class="banner_bottom_pos">
						<div class="banner_bottom_pos_grid">
							<div class="col-xs-3 banner_bottom_grid_left">
								<div class="banner_bottom_grid_left_grid">
									<div class="dodecagon b1">
										<div class="dodecagon-in b1">
											<div class="dodecagon-bg b1">
												<span class="fas fa-camera-retro" aria-hidden="true"></span>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-xs-9 banner_bottom_grid_right">
								<h4>{{project.title}}</h4>
								<p>{{project.description|truncatewords:"20"}}</p>
								<div class="barWrapper">
									<span class="progressText"><b>Completion Status</b></span>
									<div class="progress">
										<div class="progress-bar" role="progressbar" aria-valuenow="{{project.completion_pct}}" aria-valuemin="0" aria-valuemax="100">
											<span class="popOver" data-toggle="tooltip" data-placement="top" title="{{project.completion_pct}}%"> </span>
										</div>
									</div>
								</div>
							</div>


							<div class="clearfix"> </div>
						</div>
					</div>
				</div>
				{% endfor %}
				<div class="clearfix"></div>
			</div>
	</div>
</div>



{% endblock %}

templates/clienttemplates/clienttearsheet.html
{% extends 'clienttemplates/base.html' %}
{% block abc %}active{% endblock %}


{% block content %}
<div class="banner_top">
		<div id="myCarousel" class="carousel slide" data-ride="carousel">
		</div>

	</div>

	<div class="works" id="services">
		<div class="container">
			<h3 class="tittle_w3ls cen">Tear Sheet</h3>
		</div>
	</div>

	<!--//photographers-->
	<div class="gallery_sec" id="gallery">
		{% for tearsheet in alltearsheet %}
		<div class="col-md-4 col-sm-4 col-xs-4 gal-sec">
			<div class="gallery-grid1">
				<a title="" href="{{tearsheet.image.url}}">
						<img src="{{tearsheet.image.url}}" alt=" " class="img-responsive" />
						</a>
			</div>
		</div>
		{% endfor %}
</div>
{% endblock %}

templates/clienttemplates/contact.html
{% extends 'clienttemplates/base.html' %}

{% block contact %}active{% endblock %}


{% block content %}
<div class="works" id="services">
		<div class="container">
			<h3 class="tittle_w3ls cen">Contant Me</h3>
		</div>
	</div>

{% endblock %}


{% block footer %}

<div class="responsive_tabs">
				<div id="horizontalTab">
					<ul class="resp-tabs-list">
						<li>Contact Info</li>
						<li>Send Message</li>
						<li>View Map</li>
					</ul>
					<div class="resp-tabs-container">
						<!--/tab_one-->
						<div class="tab1">
							<div class="tab-info">

								<div class="address">
									<div class="col-md-4 address-grid-w3ls-agile">
										<div class="address-left">
											<div class="dodecagon f1">
												<div class="dodecagon-in f1">
													<div class="dodecagon-bg f1">
														<span class="fas fa-phone-volume" aria-hidden="true"></span>
													</div>
												</div>
											</div>
										</div>
										<div class="address-right">
											<h6>Phone Number</h6>
											<p>{{persinfo.mobile}}</p>

										</div>
										<div class="clearfix"> </div>
									</div>
									<div class="col-md-4 address-grid-w3ls-agile">
										<div class="address-left">
											<div class="dodecagon f1">
												<div class="dodecagon-in f1">
													<div class="dodecagon-bg f1">
														<span class="far fa-envelope" aria-hidden="true"></span>
													</div>
												</div>
											</div>
										</div>
										<div class="address-right">
											<h6>Email Address</h6>
											<p>Email :<a href="mailto:{{persinfo.email}}"> {{persinfo.email}}</a></p>
										</div>
										<div class="clearfix"> </div>
									</div>
									<div class="col-md-4 address-grid-w3ls-agile">
										<div class="address-left">
											<div class="dodecagon f1">
												<div class="dodecagon-in f1">
													<div class="dodecagon-bg f1">
														<span class="fas fa-map-marker-alt" aria-hidden="true"></span>
													</div>
												</div>
											</div>
										</div>
										<div class="address-right">
											<h6>Location</h6>
											<p>{{persinfo.address}}

											</p>
										</div>
										<div class="clearfix"> </div>
									</div>
									<div class="clearfix"> </div>
								</div>
							</div>
						</div>
						<!--//tab_one-->
						<div class="tab2">

							<div class="tab-info">
								<div class="contact_grid_right">
									<h6>Please fill this form to contact with us.</h6>
									<form action="#" method="post">
										<div class="contact_left_grid">
											<input type="text" name="Name" placeholder="Name" required="">
											<input type="email" name="Email" placeholder="Email" required="">

											<input type="text" name="Telephone" placeholder="Telephone" required="">
											<input type="text" name="Subject" placeholder="Subject" required="">
											<textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
											<input type="submit" value="Submit">
											<input type="reset" value="Clear">
											<div class="clearfix"> </div>
										</div>
									</form>
								</div>
							</div>
						</div>
						<!--//tab_two-->
						<div class="tab3">

							<div class="tab-info">
								<div class="contact-map-wthree-agileits">

									<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d100949.24429313939!2d-122.44206553967531!3d37.75102885910819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80859a6d00690021%3A0x4a501367f076adff!2sSan+Francisco%2C+CA%2C+USA!5e0!3m2!1sen!2sin!4v1472190196783"
									    class="map" style="border:0" allowfullscreen=""></iframe>
								</div>

							</div>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			</div>

{% endblock %}